// src/utilities/colors.js
export const colors = [
	{ label: 'Primary', value: 'primary' },
	{ label: 'Dark', value: 'dark' },
	{ label: 'Light', value: 'light' },
	{ label: 'Yellow', value: 'yellow' },
	{ label: 'Orange', value: 'orange' },
	{ label: 'Red', value: 'red' },
	{ label: 'Pink', value: 'pink' },
	{ label: 'Fuchsia', value: 'fuchsia' },
	{ label: 'Violet', value: 'violet' },
	{ label: 'Purple', value: 'purple' },
	{ label: 'Blue', value: 'blue' },
	{ label: 'Aqua', value: 'aqua' },
	{ label: 'Sky', value: 'sky' },
	{ label: 'Green', value: 'green' },
	{ label: 'Leaf', value: 'leaf' },
	{ label: 'Ash', value: 'ash' },
	{ label: 'Navy', value: 'navy' },
	{ label: 'Grape', value: 'grape' },
	{ label: 'Muted', value: 'muted' },
	{ label: 'White', value: 'white' },
	{ label: 'Pinterest', value: 'pinterest' },
	{ label: 'Dewalt', value: 'dewalt' },
	{ label: 'Facebook', value: 'facebook' },
	{ label: 'Telegram', value: 'telegram' },
	{ label: 'Frost', value: 'frost' },
];


