// svg_icons.js
// SVG иконки из темы Sandbox/codeweber

/**
 * Lineal SVG иконки (контурные)
 * Путь: /assets/img/icons/lineal/{value}.svg
 */
export const svgIconsLineal = [
	{ value: 'adjust', label: 'Adjust' },
	{ value: 'agenda', label: 'Agenda' },
	{ value: 'analytics', label: 'Analytics' },
	{ value: 'award', label: 'Award' },
	{ value: 'award-2', label: 'Award 2' },
	{ value: 'badge', label: 'Badge' },
	{ value: 'balance', label: 'Balance' },
	{ value: 'bar-chart', label: 'Bar Chart' },
	{ value: 'barcode', label: 'Barcode' },
	{ value: 'bell', label: 'Bell' },
	{ value: 'box', label: 'Box' },
	{ value: 'briefcase', label: 'Briefcase' },
	{ value: 'briefcase-2', label: 'Briefcase 2' },
	{ value: 'browser', label: 'Browser' },
	{ value: 'browser-2', label: 'Browser 2' },
	{ value: 'brush', label: 'Brush' },
	{ value: 'bucket', label: 'Bucket' },
	{ value: 'cake', label: 'Cake' },
	{ value: 'calculator', label: 'Calculator' },
	{ value: 'calendar', label: 'Calendar' },
	{ value: 'certificate', label: 'Certificate' },
	{ value: 'chat', label: 'Chat' },
	{ value: 'chat-2', label: 'Chat 2' },
	{ value: 'check', label: 'Check' },
	{ value: 'check-2', label: 'Check 2' },
	{ value: 'check-list', label: 'Check List' },
	{ value: 'clipboard', label: 'Clipboard' },
	{ value: 'clock', label: 'Clock' },
	{ value: 'clock-2', label: 'Clock 2' },
	{ value: 'clock-3', label: 'Clock 3' },
	{ value: 'cloud-computing', label: 'Cloud Computing' },
	{ value: 'cloud-computing-2', label: 'Cloud Computing 2' },
	{ value: 'cloud-computing-3', label: 'Cloud Computing 3' },
	{ value: 'coffee-cup', label: 'Coffee Cup' },
	{ value: 'coin', label: 'Coin' },
	{ value: 'compass', label: 'Compass' },
	{ value: 'computer', label: 'Computer' },
	{ value: 'controller', label: 'Controller' },
	{ value: 'controller-2', label: 'Controller 2' },
	{ value: 'crayons', label: 'Crayons' },
	{ value: 'crop', label: 'Crop' },
	{ value: 'design', label: 'Design' },
	{ value: 'directions', label: 'Directions' },
	{ value: 'discount-tag', label: 'Discount Tag' },
	{ value: 'download', label: 'Download' },
	{ value: 'earth', label: 'Earth' },
	{ value: 'edit-text', label: 'Edit Text' },
	{ value: 'email', label: 'Email' },
	{ value: 'email-2', label: 'Email 2' },
	{ value: 'email-3', label: 'Email 3' },
	{ value: 'exchange', label: 'Exchange' },
	{ value: 'expand', label: 'Expand' },
	{ value: 'fax', label: 'Fax' },
	{ value: 'files', label: 'Files' },
	{ value: 'fullscreen', label: 'Fullscreen' },
	{ value: 'geolocalization', label: 'Geolocalization' },
	{ value: 'gift', label: 'Gift' },
	{ value: 'group', label: 'Group' },
	{ value: 'group-2', label: 'Group 2' },
	{ value: 'growth', label: 'Growth' },
	{ value: 'handshake', label: 'Handshake' },
	{ value: 'headphone', label: 'Headphone' },
	{ value: 'headphone-2', label: 'Headphone 2' },
	{ value: 'heart', label: 'Heart' },
	{ value: 'home', label: 'Home' },
	{ value: 'hourglass', label: 'Hourglass' },
	{ value: 'house', label: 'House' },
	{ value: 'id-card', label: 'ID Card' },
	{ value: 'insurance', label: 'Insurance' },
	{ value: 'invoice', label: 'Invoice' },
	{ value: 'laptop', label: 'Laptop' },
	{ value: 'levels', label: 'Levels' },
	{ value: 'light-bulb', label: 'Light Bulb' },
	{ value: 'link', label: 'Link' },
	{ value: 'list', label: 'List' },
	{ value: 'loading', label: 'Loading' },
	{ value: 'lock', label: 'Lock' },
	{ value: 'login', label: 'Login' },
	{ value: 'logout', label: 'Logout' },
	{ value: 'loss', label: 'Loss' },
	{ value: 'loyalty', label: 'Loyalty' },
	{ value: 'map', label: 'Map' },
	{ value: 'maximize', label: 'Maximize' },
	{ value: 'medal', label: 'Medal' },
	{ value: 'meeting', label: 'Meeting' },
	{ value: 'megaphone', label: 'Megaphone' },
	{ value: 'menu', label: 'Menu' },
	{ value: 'microphone', label: 'Microphone' },
	{ value: 'minimize', label: 'Minimize' },
	{ value: 'money', label: 'Money' },
	{ value: 'music', label: 'Music' },
	{ value: 'networking', label: 'Networking' },
	{ value: 'networking-2', label: 'Networking 2' },
	{ value: 'open', label: 'Open' },
	{ value: 'padlock', label: 'Padlock' },
	{ value: 'paint-roller', label: 'Paint Roller' },
	{ value: 'paper', label: 'Paper' },
	{ value: 'paper-plane', label: 'Paper Plane' },
	{ value: 'password', label: 'Password' },
	{ value: 'photo-camera', label: 'Photo Camera' },
	{ value: 'picture', label: 'Picture' },
	{ value: 'pictures', label: 'Pictures' },
	{ value: 'pie-chart', label: 'Pie Chart' },
	{ value: 'pie-chart-2', label: 'Pie Chart 2' },
	{ value: 'pin', label: 'Pin' },
	{ value: 'pin-2', label: 'Pin 2' },
	{ value: 'plan', label: 'Plan' },
	{ value: 'price-tag', label: 'Price Tag' },
	{ value: 'printer', label: 'Printer' },
	{ value: 'profits', label: 'Profits' },
	{ value: 'puzzle', label: 'Puzzle' },
	{ value: 'puzzle-2', label: 'Puzzle 2' },
	{ value: 'ranking', label: 'Ranking' },
	{ value: 'refresh', label: 'Refresh' },
	{ value: 'rocket', label: 'Rocket' },
	{ value: 'savings', label: 'Savings' },
	{ value: 'scale', label: 'Scale' },
	{ value: 'scroll', label: 'Scroll' },
	{ value: 'scroll-2', label: 'Scroll 2' },
	{ value: 'search', label: 'Search' },
	{ value: 'search-2', label: 'Search 2' },
	{ value: 'server', label: 'Server' },
	{ value: 'settings', label: 'Settings' },
	{ value: 'settings-2', label: 'Settings 2' },
	{ value: 'settings-3', label: 'Settings 3' },
	{ value: 'shield', label: 'Shield' },
	{ value: 'shield-2', label: 'Shield 2' },
	{ value: 'shop', label: 'Shop' },
	{ value: 'shop-2', label: 'Shop 2' },
	{ value: 'shope-3', label: 'Shop 3' },
	{ value: 'shopping-basket', label: 'Shopping Basket' },
	{ value: 'shopping-cart', label: 'Shopping Cart' },
	{ value: 'show', label: 'Show' },
	{ value: 'sitemap', label: 'Sitemap' },
	{ value: 'smartphone', label: 'Smartphone' },
	{ value: 'smartphone-2', label: 'Smartphone 2' },
	{ value: 'smartphone-3', label: 'Smartphone 3' },
	{ value: 'smartphone-4', label: 'Smartphone 4' },
	{ value: 'smartwatch', label: 'Smartwatch' },
	{ value: 'speedometer', label: 'Speedometer' },
	{ value: 'square', label: 'Square' },
	{ value: 'stars', label: 'Stars' },
	{ value: 'startup', label: 'Startup' },
	{ value: 'statistics', label: 'Statistics' },
	{ value: 'sticker', label: 'Sticker' },
	{ value: 'target', label: 'Target' },
	{ value: 'target-2', label: 'Target 2' },
	{ value: 'team', label: 'Team' },
	{ value: 'telemarketer', label: 'Telemarketer' },
	{ value: 'telephone', label: 'Telephone' },
	{ value: 'telephone-2', label: 'Telephone 2' },
	{ value: 'telephone-3', label: 'Telephone 3' },
	{ value: 'television', label: 'Television' },
	{ value: 'tie', label: 'Tie' },
	{ value: 'tools', label: 'Tools' },
	{ value: 'touch-screen', label: 'Touch Screen' },
	{ value: 'truck', label: 'Truck' },
	{ value: 'upload', label: 'Upload' },
	{ value: 'user', label: 'User' },
	{ value: 'video', label: 'Video' },
	{ value: 'video-2', label: 'Video 2' },
	{ value: 'video-camera', label: 'Video Camera' },
	{ value: 'video-editing', label: 'Video Editing' },
	{ value: 'wallet', label: 'Wallet' },
	{ value: 'watercolor', label: 'Watercolor' },
	{ value: 'web', label: 'Web' },
	{ value: 'workflow', label: 'Workflow' },
];

/**
 * Solid SVG иконки (заполненные)
 * Путь: /assets/img/icons/solid/{value}.svg
 */
export const svgIconsSolid = [
	{ value: '3d', label: '3D' },
	{ value: 'alarm', label: 'Alarm' },
	{ value: 'audience', label: 'Audience' },
	{ value: 'badge', label: 'Badge' },
	{ value: 'bar-chart', label: 'Bar Chart' },
	{ value: 'bar-chart-2', label: 'Bar Chart 2' },
	{ value: 'bell', label: 'Bell' },
	{ value: 'briefcase', label: 'Briefcase' },
	{ value: 'bucket', label: 'Bucket' },
	{ value: 'building', label: 'Building' },
	{ value: 'bulb', label: 'Bulb' },
	{ value: 'bullhorn', label: 'Bullhorn' },
	{ value: 'calendar', label: 'Calendar' },
	{ value: 'camera', label: 'Camera' },
	{ value: 'chatting', label: 'Chatting' },
	{ value: 'chatting-2', label: 'Chatting 2' },
	{ value: 'checked', label: 'Checked' },
	{ value: 'clipboard', label: 'Clipboard' },
	{ value: 'cloud-download', label: 'Cloud Download' },
	{ value: 'cloud-group', label: 'Cloud Group' },
	{ value: 'cloud-network', label: 'Cloud Network' },
	{ value: 'cloud-network-2', label: 'Cloud Network 2' },
	{ value: 'cloud-transfer', label: 'Cloud Transfer' },
	{ value: 'code', label: 'Code' },
	{ value: 'coffee-cup', label: 'Coffee Cup' },
	{ value: 'coin', label: 'Coin' },
	{ value: 'coin-decrease', label: 'Coin Decrease' },
	{ value: 'coin-lock', label: 'Coin Lock' },
	{ value: 'coin-reload', label: 'Coin Reload' },
	{ value: 'coin-rise', label: 'Coin Rise' },
	{ value: 'compare', label: 'Compare' },
	{ value: 'computer', label: 'Computer' },
	{ value: 'conference', label: 'Conference' },
	{ value: 'content', label: 'Content' },
	{ value: 'controls', label: 'Controls' },
	{ value: 'controls-2', label: 'Controls 2' },
	{ value: 'crop', label: 'Crop' },
	{ value: 'crosshair', label: 'Crosshair' },
	{ value: 'currency', label: 'Currency' },
	{ value: 'deal', label: 'Deal' },
	{ value: 'delivery-box', label: 'Delivery Box' },
	{ value: 'devices', label: 'Devices' },
	{ value: 'director', label: 'Director' },
	{ value: 'discussion', label: 'Discussion' },
	{ value: 'dot', label: 'Dot' },
	{ value: 'double-click', label: 'Double Click' },
	{ value: 'e-commerce', label: 'E-Commerce' },
	{ value: 'edit', label: 'Edit' },
	{ value: 'edit-2', label: 'Edit 2' },
	{ value: 'email-2', label: 'Email' },
	{ value: 'emails', label: 'Emails' },
	{ value: 'employees', label: 'Employees' },
	{ value: 'feather', label: 'Feather' },
	{ value: 'gamepad', label: 'Gamepad' },
	{ value: 'gears', label: 'Gears' },
	{ value: 'globe-2', label: 'Globe' },
	{ value: 'graph', label: 'Graph' },
	{ value: 'headphone', label: 'Headphone' },
	{ value: 'health-insurance', label: 'Health Insurance' },
	{ value: 'image', label: 'Image' },
	{ value: 'images', label: 'Images' },
	{ value: 'infographic', label: 'Infographic' },
	{ value: 'lamp', label: 'Lamp' },
	{ value: 'layers', label: 'Layers' },
	{ value: 'layout', label: 'Layout' },
	{ value: 'layout-2', label: 'Layout 2' },
	{ value: 'layout-3', label: 'Layout 3' },
	{ value: 'like', label: 'Like' },
	{ value: 'link', label: 'Link' },
	{ value: 'list', label: 'List' },
	{ value: 'lock', label: 'Lock' },
	{ value: 'love', label: 'Love' },
	{ value: 'marker', label: 'Marker' },
	{ value: 'mask', label: 'Mask' },
	{ value: 'medal', label: 'Medal' },
	{ value: 'monitor', label: 'Monitor' },
	{ value: 'navigation', label: 'Navigation' },
	{ value: 'network', label: 'Network' },
	{ value: 'note', label: 'Note' },
	{ value: 'paint', label: 'Paint' },
	{ value: 'paper-plane', label: 'Paper Plane' },
	{ value: 'partnership', label: 'Partnership' },
	{ value: 'pen-tool', label: 'Pen Tool' },
	{ value: 'pie-chart', label: 'Pie Chart' },
	{ value: 'pin', label: 'Pin' },
	{ value: 'plane', label: 'Plane' },
	{ value: 'price-tag', label: 'Price Tag' },
	{ value: 'printer', label: 'Printer' },
	{ value: 'push-cart', label: 'Push Cart' },
	{ value: 'puzzle', label: 'Puzzle' },
	{ value: 'rocket', label: 'Rocket' },
	{ value: 'roller', label: 'Roller' },
	{ value: 'rotary', label: 'Rotary' },
	{ value: 'safe', label: 'Safe' },
	{ value: 'script', label: 'Script' },
	{ value: 'search', label: 'Search' },
	{ value: 'secure', label: 'Secure' },
	{ value: 'selected', label: 'Selected' },
	{ value: 'seo', label: 'SEO' },
	{ value: 'seo-2', label: 'SEO 2' },
	{ value: 'server', label: 'Server' },
	{ value: 'setting', label: 'Setting' },
	{ value: 'share', label: 'Share' },
	{ value: 'sharing', label: 'Sharing' },
	{ value: 'shipment', label: 'Shipment' },
	{ value: 'shopping-bag', label: 'Shopping Bag' },
	{ value: 'shopping-basket', label: 'Shopping Basket' },
	{ value: 'shopping-cart', label: 'Shopping Cart' },
	{ value: 'smartphone', label: 'Smartphone' },
	{ value: 'supermarket', label: 'Supermarket' },
	{ value: 'synchronize', label: 'Synchronize' },
	{ value: 'target', label: 'Target' },
	{ value: 'team', label: 'Team' },
	{ value: 'toggle', label: 'Toggle' },
	{ value: 'touchscreen', label: 'Touchscreen' },
	{ value: 'transfer', label: 'Transfer' },
	{ value: 'travel-insurance', label: 'Travel Insurance' },
	{ value: 'tv-screen', label: 'TV Screen' },
	{ value: 'verify', label: 'Verify' },
	{ value: 'video-chat', label: 'Video Chat' },
	{ value: 'video-player', label: 'Video Player' },
	{ value: 'videocall', label: 'Videocall' },
	{ value: 'videocall-2', label: 'Videocall 2' },
	{ value: 'wallet', label: 'Wallet' },
	{ value: 'web-browser', label: 'Web Browser' },
	{ value: 'web-programming', label: 'Web Programming' },
];

/**
 * Все SVG иконки (объединённый массив с категориями)
 */
export const allSvgIcons = [
	...svgIconsLineal.map((icon) => ({ ...icon, category: 'lineal' })),
	...svgIconsSolid.map((icon) => ({ ...icon, category: 'solid' })),
];

/**
 * Стили SVG иконок
 */
export const svgIconStyles = [
	{ value: 'lineal', label: 'Lineal (контурные)' },
	{ value: 'solid', label: 'Solid (заполненные)' },
	{ value: 'solid-mono', label: 'Solid Mono (одноцветные)' },
	{ value: 'solid-duo', label: 'Solid Duo (двухцветные)' },
];

/**
 * Получить путь к SVG иконке
 * @param {string} iconName - Название иконки
 * @param {string} style - Стиль (lineal, solid, solid-mono, solid-duo)
 * @returns {string} - Путь к иконке
 */
export const getSvgIconPath = (iconName, style = 'lineal') => {
	const folder = style === 'lineal' ? 'lineal' : 'solid';
	return `/wp-content/themes/codeweber/dist/assets/img/icons/${folder}/${iconName}.svg`;
};

